apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: memcached-chart
spec:
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts/memcached
  ref:
    semver: 7.9.7 # {"$imagepolicy": "apps:backend-memcached:tag"}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: memcached
spec:
  releaseName: memcached
  chartRef:
    kind: OCIRepository
    name: memcached-chart
  interval: 50m
  driftDetection:
    mode: disabled
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
  # Default values
  # https://artifacthub.io/packages/helm/bitnami/memcached?modal=values
  values:
    clusterDomain: cluster.local
